#!/bin/bash

# Script de ayuda para deployment en Railway + Vercel
# Uso: ./scripts/deployment-helpers.sh [comando]

set -e

# Colores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Función para imprimir con color
print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Función para generar secrets
generate_secrets() {
    print_info "Generando secrets seguros..."
    echo ""
    echo "================================================"
    echo "JWT SECRET:"
    echo "================================================"
    openssl rand -base64 64
    echo ""
    print_success "JWT Secret generado!"
}

# Función para verificar configuración local
check_local_setup() {
    print_info "Verificando configuración local..."
    
    # Verificar Git
    if ! command -v git &> /dev/null; then
        print_error "Git no está instalado"
        exit 1
    fi
    print_success "Git instalado"
    
    # Verificar que estamos en un repositorio Git
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        print_error "No estás en un repositorio Git"
        exit 1
    fi
    print_success "Repositorio Git detectado"
    
    # Verificar que hay un remote
    if ! git remote -v | grep -q "origin"; then
        print_warning "No hay remote 'origin' configurado"
        print_info "Configura tu repositorio de GitHub primero"
    else
        print_success "Remote 'origin' configurado"
    fi
    
    # Verificar archivos necesarios
    if [ ! -f "Dockerfile" ]; then
        print_error "Dockerfile no encontrado en la raíz"
        exit 1
    fi
    print_success "Dockerfile encontrado"
    
    if [ ! -f "vercel.json" ]; then
        print_error "vercel.json no encontrado"
        exit 1
    fi
    print_success "vercel.json encontrado"
    
    if [ ! -f "railway.json" ]; then
        print_error "railway.json no encontrado"
        exit 1
    fi
    print_success "railway.json encontrado"
    
    print_success "Configuración local verificada!"
}

# Función para crear .env.production del frontend
create_frontend_env() {
    print_info "Creando frontend/.env.production..."
    
    read -p "Ingresa la URL de tu backend en Railway (ej: https://tu-app.up.railway.app): " BACKEND_URL
    
    if [ -z "$BACKEND_URL" ]; then
        print_error "URL del backend es requerida"
        exit 1
    fi
    
    # Remover trailing slash si existe
    BACKEND_URL=${BACKEND_URL%/}
    
    # Crear archivo .env.production
    cat > frontend/.env.production << EOF
# Production Environment Variables
# Generated by deployment-helpers.sh

# Backend API URL (Railway)
VITE_API_BASE_URL=${BACKEND_URL}/api

# WebSocket URL (Railway)
VITE_WS_URL=${BACKEND_URL/https/wss}/ws
EOF
    
    print_success "frontend/.env.production creado!"
    print_info "Contenido:"
    cat frontend/.env.production
    echo ""
    print_warning "Recuerda hacer commit y push de este archivo"
}

# Función para verificar el backend
check_backend() {
    print_info "Verificando backend..."
    
    read -p "Ingresa la URL de tu backend en Railway: " BACKEND_URL
    
    if [ -z "$BACKEND_URL" ]; then
        print_error "URL del backend es requerida"
        exit 1
    fi
    
    # Remover trailing slash
    BACKEND_URL=${BACKEND_URL%/}
    
    print_info "Verificando health endpoint..."
    
    if curl -f -s "${BACKEND_URL}/actuator/health" > /dev/null; then
        print_success "Backend está funcionando!"
        echo ""
        print_info "Respuesta:"
        curl -s "${BACKEND_URL}/actuator/health" | python3 -m json.tool 2>/dev/null || curl -s "${BACKEND_URL}/actuator/health"
    else
        print_error "Backend no responde o no está saludable"
        print_info "Verifica los logs en Railway"
        exit 1
    fi
}

# Función para verificar el frontend
check_frontend() {
    print_info "Verificando frontend..."
    
    read -p "Ingresa la URL de tu frontend en Vercel: " FRONTEND_URL
    
    if [ -z "$FRONTEND_URL" ]; then
        print_error "URL del frontend es requerida"
        exit 1
    fi
    
    # Remover trailing slash
    FRONTEND_URL=${FRONTEND_URL%/}
    
    print_info "Verificando que el frontend carga..."
    
    if curl -f -s "${FRONTEND_URL}" > /dev/null; then
        print_success "Frontend está funcionando!"
    else
        print_error "Frontend no responde"
        print_info "Verifica el deployment en Vercel"
        exit 1
    fi
}

# Función para mostrar checklist
show_checklist() {
    cat << 'EOF'
📋 CHECKLIST DE DEPLOYMENT

PRE-DEPLOYMENT:
□ Código en GitHub
□ Cuenta en Railway
□ Cuenta en Vercel
□ Secrets generados

RAILWAY - BACKEND:
□ Proyecto creado
□ PostgreSQL agregado
□ Redis agregado
□ Variables de entorno configuradas
□ Backend deployado
□ Health check pasando

VERCEL - FRONTEND:
□ Proyecto importado
□ Root directory: frontend
□ Variables de entorno configuradas
□ Frontend deployado
□ Página carga correctamente

CONEXIÓN:
□ CORS actualizado en Railway
□ Frontend se conecta al backend
□ Login funciona
□ Crear proyecto funciona

POST-DEPLOYMENT:
□ URL agregada al README
□ Portafolio actualizado
□ Métricas verificadas

EOF
}

# Función para mostrar variables de entorno de Railway
show_railway_vars() {
    cat << 'EOF'
📝 VARIABLES DE ENTORNO PARA RAILWAY

Copia estas variables en Railway → Variables:

SPRING_PROFILES_ACTIVE=prod
DB_USERNAME=${{Postgres.PGUSER}}
DB_PASSWORD=${{Postgres.PGPASSWORD}}
DATABASE_URL=jdbc:postgresql://${{Postgres.PGHOST}}:${{Postgres.PGPORT}}/${{Postgres.PGDATABASE}}
REDIS_HOST=${{Redis.REDIS_HOST}}
REDIS_PORT=${{Redis.REDIS_PORT}}
REDIS_PASSWORD=${{Redis.REDIS_PASSWORD}}
JWT_SECRET=<generar con: openssl rand -base64 64>
JWT_EXPIRATION=86400000
JWT_REFRESH_EXPIRATION=604800000
CORS_ALLOWED_ORIGINS=https://tu-app.vercel.app
AUTH_RATE_LIMIT=10
API_RATE_LIMIT=100
LOG_LEVEL=INFO
PORT=8080

⚠️  IMPORTANTE:
1. Reemplaza JWT_SECRET con un valor generado
2. Actualiza CORS_ALLOWED_ORIGINS con tu URL de Vercel
3. Railway reemplazará automáticamente las referencias ${{...}}

EOF
}

# Función para mostrar variables de entorno de Vercel
show_vercel_vars() {
    cat << 'EOF'
📝 VARIABLES DE ENTORNO PARA VERCEL

Copia estas variables en Vercel → Settings → Environment Variables:

VITE_API_BASE_URL=https://tu-app.up.railway.app/api
VITE_WS_URL=wss://tu-app.up.railway.app/ws

⚠️  IMPORTANTE:
Reemplaza 'tu-app.up.railway.app' con tu URL real de Railway

EOF
}

# Función para mostrar ayuda
show_help() {
    cat << 'EOF'
🚀 Deployment Helpers - Railway + Vercel

USO:
    ./scripts/deployment-helpers.sh [comando]

COMANDOS:

    secrets              Generar secrets seguros (JWT, passwords)
    check-local          Verificar configuración local
    create-frontend-env  Crear frontend/.env.production
    check-backend        Verificar que el backend funciona
    check-frontend       Verificar que el frontend funciona
    checklist            Mostrar checklist de deployment
    railway-vars         Mostrar variables de entorno para Railway
    vercel-vars          Mostrar variables de entorno para Vercel
    help                 Mostrar esta ayuda

EJEMPLOS:

    # Generar JWT secret
    ./scripts/deployment-helpers.sh secrets

    # Verificar configuración local antes de deployar
    ./scripts/deployment-helpers.sh check-local

    # Crear archivo de entorno del frontend
    ./scripts/deployment-helpers.sh create-frontend-env

    # Verificar que el backend funciona
    ./scripts/deployment-helpers.sh check-backend

    # Ver checklist completo
    ./scripts/deployment-helpers.sh checklist

DOCUMENTACIÓN:
    Ver docs/PRODUCTION_DEPLOYMENT.md para guía completa

EOF
}

# Main
case "${1:-help}" in
    secrets)
        generate_secrets
        ;;
    check-local)
        check_local_setup
        ;;
    create-frontend-env)
        create_frontend_env
        ;;
    check-backend)
        check_backend
        ;;
    check-frontend)
        check_frontend
        ;;
    checklist)
        show_checklist
        ;;
    railway-vars)
        show_railway_vars
        ;;
    vercel-vars)
        show_vercel_vars
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        print_error "Comando desconocido: $1"
        echo ""
        show_help
        exit 1
        ;;
esac
